### ISSUE TITLE
Is the project abandoned?

### ISSUE THREAD

**Issue by Nuxssss** [Ongy/waymonad#44]
The last commit was 21 Apr 2019. Does this mean that the project is abandoned?

**Comment by KiranWells** [comment]
I hope not. If it is, maybe someone is willing to make a new fork and resume development? I know very little Haskell, but I am familiar with xMonad and I am interested in helping.

**Comment by Anton-Latukha** [comment]
`xmonad` has no plans and no design to go Wayland, as everybody heard.

I think when this thing gets basics working and project docs/install gets a bit polished, there would probably be many people to create a sizable community for the project.
And when it gets working enough - all the Haskellers that started using it would develop it.

If the maintainer/creator is impossible to reach and so the transfer is not possible - then hard fork is great in this situation.

This project uses `hsroots` library which is a `wlroots`, the creator of which is a very responsive and collaborative guy, they do standardization/comune work for `wlroots` with KDE KWin team to have a good Wayland interface and support.

Doing fork is especially great, since *this project is not on Hackage: https://hoogle.haskell.org/?hoogle=waymonad. And I think people mostly go through Hackage to find upstream of a package.

Hackage release of it and Reddit ? Twitter news on it can create a cumulative situation. There are 59 watchers just here right now.

**Comment by Anton-Latukha** [comment]
I personally can look into:
  * CI
  * Provisioning of the dev env for Haskell folks that use Nix, so those would be happy
  * Having Nix env can ease-out some of the project process ramping-up, since the dependencies probably got old, Nix having local transparent environment that loads automatically during dev and supplies the particular old versions of dependencies specifically only for `waymonad` dev env and does not changes env on the system. Well, that may be beneficial for the initial period, until the project starts to support up-to-date deps.
  * Provide support for the project & its package in Nixpkgs.
  * Nix-specific CI builds and so on: optional checking that Nix dev env works
  * If things go far enough - the Nixpkgs option to just install it automatically on NixOS, so community there would start using it there.

**Comment by eddsalkield** [comment]
It is indeed interesting that there are still quite a few people wanting this project to succeed - myself included.

A project I've been meaning to get around to for a while is a minimally-opinionated wlroots wrapper that implements a Wayland server to handle displaying windows, seat management, scaling, etc. - all the standard pieces that nearly every window manager wants.  The customisable part would be the layout algorithm, expressing the end-user behaviour of the window manager.

I'm wondering whether Haskell would be an interesting language to write this in.  The waymonad codebase needs refactoring anyway, so if there's interest it could be separated in this way.

**Comment by willat8** [comment]
I really want to see this project succeed too.
If it helps anyone I have a docker build here: https://bitbucket.org/willat8/docker-waymonad/src/master/

What's really stopping me using waymonad day-to-day is the (lack of?) egl support.

**Comment by roosemberth** [comment]
I join Edd here, I would really like to have the extensibility of xmonad
on wayland in particular layout algorithms but also stuff like
layoutSplitScreen and viewports.

Unfortunatelly I don't have the time right now to take a major role in its
development :(

I really hope this project gets some love.

Quoting Edd Salkield (2021-02-04 18:41:52)

**Comment by Anton-Latukha** [comment]
<details><summary> About EGL, I hope it is not EGLstreams, because it is Nvidia's job to support new standard interfaces. </summary>
<p>

> What's really stopping me using waymonad day-to-day is the (lack of?) egl support.

Well. To be thorough for most of cases. That Nvidia that does not support Wayland standards stops from using it with Wayland.

https://drewdevault.com/2019/02/10/Wayland-misconceptions-debunked.html

> #### Wayland doesn’t support Nvidia!
> 
> Actually, Nvidia doesn’t support us. There are three standard APIs which are implemented by all graphics drivers in the Linux kernel: DRM (display resource management), KMS (kernel mode setting), and GBM (generic buffer management). All three are necessary for most Wayland compositors. Only the first two are implemented by the Nvidia proprietary driver. In order to support Nvidia, Wayland compositors need to add code resembling this:
> 
> ```C
> if (nvidia proprietary driver) {
>     /* several thousand lines of code */
> } else {
>     /* several thousand lines of code */
> }
> ```
>
> That’s terrible! On top of that, we cannot debug the proprietary driver, we cannot send fixes upstream, and we cannot read the code to understand its behavior. The mesa code (where much of the important code for many drivers lives) is a frequent object of study among Wayland compositor developers. We cannot do this with the proprietary drivers, and it doesn’t even implement the APIs it needs to. They claim to be working on a replacement for GBM which they hope will satisfy everyone’s concerns, but 52 commits in 3 years with over a year of inactivity isn’t a great sign.

I personally happen to have a Nvidia card embedded in the only laptop, and despite having powerful i7 GPU there, the graphic bus is hardwired directly to the Nvidia card, so I can not preserve battery by using integrated graphics for example.

So when Linux engineers merged into the Kernel the protection against the "Nvidia GPL condom" (actual literal term in the Kernel community), many users fell back, but I had no GPU to fall back on, so lived in the console, for some days. And I think that was completely fair, I just happened to have an Nvidia which does not collaborate proprietary bane card as my only option, and I know what the "Kernel is tainted" message means.

</details>

**Comment by KiranWells** [comment]
I would be more than happy to work on the documentation, and when I am more comfortable working with Haskell, contributing code.

**Comment by Anton-Latukha** [comment]
<details><summary> Observation on doc contributions </summary>
<p>

> I would be more than happy to work on the documentation

Yes, people, please - approach to the documentation very openly. And it is waaay better to maybe somewhat skimm on the doc quality to merge docs proactively, apply own `maintainer` edits on top in the PR, or after the merge. Because my exp is that dev review docs as code review and do nitpicks, while in the `master` is no docs. Docs are much more difficult to pass the maintainer merge than the code without the docs, maintainers seem to have no problems merging the code without docs, but the docs - "here we can nitpick and opinionate contributors speech into oblivion", and so quite often person spent quite a time making docs but the doc merges happen rarely if ever because of the maintainer stubbornness to merge ~80-98% quality while in the `master` quality is 0% (no any help docs and explanations what so ever).

So please apply "good enough, better then Void that is in `master`" policy to merging docs, and fix them on merge, or right after - there is a editor on GitHub to change words and when maintainer can spare bother the contributor with maintainer nits & opinions - good maintainer does so.

The secret to good docs is the rewriting paradigm, to accumulate edits faster - be opened to rewriting, ask Wikipedia.

So, please spare the doc contributions - it is rare to find people like this - that gift the docs.


</details>

**Comment by Nuxssss** [comment]
> I would be more than happy to work on the documentation, and when I am more comfortable working with Haskell, contributing code.

Cool! I can translate documentation to Russian (and Esperanto:D)

**Comment by 0reoKing** [comment]
I will just contribute to the docs when I can.

**Comment by jakeisnt** [comment]
Has anyone heard from the maintainer of the project? A fork might be worthwhile if they aren't communicative.

**Comment by KiranWells** [comment]
Has anyone been able to get this to build? I spent an hour trying to resolve dependencies, but Debian and wlroots don't seem to get along.

**Comment by willat8** [comment]
> Has anyone been able to get this to build? I spent an hour trying to resolve dependencies, but Debian and wlroots don't seem to get along.

See https://bitbucket.org/willat8/docker-waymonad/src/master/Dockerfile

**Comment by jakeisnt** [comment]
Does anyone want to step up as the maintainer for this? I'm unfortunately not very knowledgeable about Haskell, but I'd love to help maintain and contribute if someone else wants to take the wheel

**Comment by ulysses4ever** [comment]
> Has anyone been able to get this to build?

It's easy with the Nix build branch (available in #42). Unfortunately, I can't run it: seeing various crashes depending on how I start it.

**Comment by Atemu** [comment]
That PR pins Nixpkgs to a pretty old version, try overriding it with something more current.

**Comment by ghost** [comment]
I'd love to help with this as well but I'm currently on an Nvidia GPU so I don't think I can even run any Wayland :( I'm planning to setup an AMD machine in the near future though

**Comment by pjboro** [comment]
I don't know Haskell, but I could try to contribute to the docs, or help with the packaging. I love tiling WMs and there's a shortage of these on Wayland.

**Comment by colonelpanic8** [comment]
@KiranWells Did you check out my pr for building with nix. I can 100% guarantee that that will build it succesfully for you.

**Comment by colonelpanic8** [comment]
@ulysses4ever How are you trying to run it. For me when I built it using the nix pr i was able t get it started using sddm.

**Comment by colonelpanic8** [comment]
> Does anyone want to step up as the maintainer for this? I'm unfortunately not very knowledgeable about Haskell, but I'd love to help maintain and contribute if someone else wants to take the wheel

I could volunteer as the temporary maintainer of a fork. I'm relatively knowledgeable about Haskell, and was able to get everything building using nix.

**Comment by KiranWells** [comment]
Please do; I think if someone starts something it will cause more people to get involved.

**Comment by ulysses4ever** [comment]
@IvanMalison thanks for the feedback! I run it from a fresh tty without any display manager (this worked for Sway so I hoped it can with waymonad too). The problem it seems to have is  the version of glibc:

> gbm: failed to open any driver (search paths /run/opengl-driver/lib/dri)
> gbm: Last dlopen error: /nix/store/ils5w0qac35zdp050n4bspwnbciyr1iq-glibc-2.27/lib/libm.so.6: version `GLIBC_2.29' not found (required by /run/opengl-driver/lib/dri/kms_swrast_dri.so)

([full output](https://gist.github.com/ulysses4ever/a12717c1b38fa92d2f8fc9024c9335d9))

Anyways, I'd be happy if you fork this repo. I can open an issue with my problem  against the fork.

**Comment by Atemu** [comment]
@ulysses4ever  As I said, the Nixpkgs version pinned in the PR is pretty old at this point. Its glibc (v2.27) is too old to work with your system's graphics drivers which require 2.29.

Override it with the Nixpkgs version used to build your system closure (reverting 269fecbd4935aa63a81035f42690466eb415ca69 in @IvanMalison's PR should do it) or at the very least one that has glibc v2.29.

**Comment by ulysses4ever** [comment]
Thanks @Atemu! I was meant to try it just never found time for it, sorry. Just wanted to answer @IvanMalison's question in case he will be interested in fixing it on his branch directly.

**Comment by Atemu** [comment]
I just tried building it with a newer Nixpkgs but it looks like that'll require more work in #42.

**Comment by Atemu** [comment]
Yeah, so current status is:

hsroots is in dire need of an update. I don't think it'll work with anything newer than wlroots 0.5.0.

The oldest Nixpkgs release with the glibc patch that updates it >2.27 is 20.03. I've downgraded its wlroots [here](https://github.com/Atemu/nixpkgs/tree/hsroot-old-wlroots).

If you then fix up the overlays (done [here](https://github.com/Atemu/waymonad/tree/newer-nixpkgs)), you will almost get it to compile but waymonad doesn't seem to want to import `Config.Schema.Spec` properly (`Not in scope: type constructor or class ‘Spec’`) which I have no idea how to debug.  
Otherwise it should build fine and it should run now that the glibc version is less ancient.

**Comment by willat8** [comment]
You need to restrict the config-schema version: https://github.com/willat8/waymonad/commit/6bb3d63d2834fba1fe4a66b938035fd9e4b66c68

**Comment by willat8** [comment]
The latest wlroots revision hsroots works with is https://github.com/swaywm/wlroots/commit/4f4d3cf2a25f7af022e51b861ef04f7c4a94b768.

**Comment by VannTen** [comment]
I'm also interested in this project. I have no experience in Haskell yet, but that's a good opportunity to dive in :).

**Comment by FRostri** [comment]
I recently wanted to learn a bit about haskell by xmonad, now I could learn more to see if I can contribute something to the project

**Comment by rasmus-kirk** [comment]
Any news on a fork?

**Comment by ajkavanagh** [comment]
I'm really interested in this project too, and by chance, I guess I'm an 'intermediate' Haskell programmer.  I'd be interested in collaborating either here, or on a fork (or even my own fork).  My main lack of knowledge is around wayland and how it works, but I guess the best way to resolve that, is to try an work with the various components.

So @Ongy what are your current thoughts, good or bad, regarding letting this move forward.  Would you prefer a fork and then merge back in (but that means you need to review and accept PRs), or would you like some co-owners/participators in the repository, or are you essentially not interested anymore?  Some guidance would be useful before a possible 'waymonad-fork' org is started with a fork of the code.

**Comment by L-as** [comment]
How about working on this at Zurihac? Anybody up for it? Since it's online I think you can still participate even if you register now. https://zfoh.ch/zurihac2021/

**Comment by contrun** [comment]
@Ongy hasn't been active on github for a while. I searched @Ongy 's name on google (I hope @Ongy does not mind). There is no result in the past year, but there're results some time before. I think it is best for people who are interested in contributing to waymonad to first fork this repo in a new organization. When @Ongy comes back online, we can then discuss how to contribute back to this repo.

**Comment by L-as** [comment]
I sent an e-mail to him, maybe he'll answer.

**Comment by L-as** [comment]
I got into contact with him, he said he'll look into it this weekend!

**Comment by L-as** [comment]
There is a #waymonad channel on the discord server for ZuriHac if people want to join. You can still [join](https://zfoh.ch/zurihac2021/).

**Comment by L-as** [comment]
I have a fork on https://github.com/L-as/waymonad that works with Nix if people want to contribute.

You can just run `nix-shell` then `cabal repl` and fix the issues you see. I think I've fixed all the dependency issues, next is making it type check since some of the dependencies have been incompatibly updated.

**Comment by Nuxssss** [comment]
I know haskell, and I want to practice, but I do not know how I can help the project.

**Comment by KiranWells** [comment]
> I know haskell, and I want to practice, but I do not know how I can help the project.

Try downloading the project, getting it to run (I recommend using one of the container options above), then go through and start documenting what each function does, starting from main. It would help anyone else just coming to this project and it might reveal what needs to be worked on.

**Comment by L-as** [comment]
If you have Nix just running nix-shell is optimal IMO.

**Comment by DriNeo** [comment]
Hello, to help people that want to go Wayland I suggest to test Vivarium.

https://github.com/inclement/vivarium

The devs takes inspiration from XMonad.

**Comment by mathstuf** [comment]
Thanks for the link. It looks like a start with the layout and desktop semantics, but alas, the static keybinding controls gives me a lack of hope in support for `submap` prefix key combination (my "prefix" is `Ctrl-I` and behaves like `tmux`'s prefix in behavior).

**Comment by samhh** [comment]
Unfortunately a big part of the draw to xmonad for me personally is the ability to configure my WM in a language I really enjoy using. I'd rather just use Sway and embrace its lack of flexibility than have to work with C.

The best way to make something like waymonad happen is probably to [support the xmonad devs](https://github.com/sponsors/xmonad).

**Comment by DriNeo** [comment]
Sway doesn't even have autotiling. I tested Vivarium one week without using any C. The simple TOML file allowed me to choose between several kinds of autotiling. I admit I'm not an advanced user so the default choices are enough for me.
I came back to Bspwm just because some important softwares for my work, aren't native Wayland apps.

**Comment by l29ah** [comment]
> The best way to make something like waymonad happen is probably to support the xmonad devs.

Will they implement X application isolation (e.g. not being able to capture screen and log keys) that is available in Wayland?

**Comment by PRESFIL** [comment]
Ping! @Ongy recently logged in on GitHub.

**Comment by appetrosyan** [comment]
Logged in and project not abandoned isn't the same thing… sigh!

**Comment by tsilvs** [comment]
Is anyone ready to fork & maintain the project?

**Comment by Legogris** [comment]
Slightly OT but qtile has a pretty flexible tiling model and is probably the closest one can get to xmonad UX on wayland right now.  Worth checking out for users looking for an option.

**Comment by tsilvs** [comment]
How viable is to try running xmonad through xwayland?

**Comment by mathstuf** [comment]
> How viable is to try running xmonad through xwayland?

It wouldn't mean much as all Wayland windows would remain unmanaged by XMonad (as they do not talk X at all).

**Comment by liskin** [comment]
> How viable is to try running xmonad through xwayland?

There were [some XWayland patches merged last year](https://www.phoronix.com/news/XWayland-Rootfull-Desktop) related to this, but like @mathstuf said, you wouldn't actually get a Wayland xmonad. You'd just get a good old X server with the compositing (also known as "actually putting pixels on screen") stuff done by a Wayland compositor. That might still be worth it though, as X compositors are all crap. :-)

**Comment by 0xadeeb** [comment]
Why is that no one even knows if the project is abandoned or not?

**Comment by ajkavanagh** [comment]
> Why is that no one even knows if the project is abandoned or not?

I would say that this answers itself; the project is almost certainly *de facto* abandoned, even if it has not been formally abandoned.

**Comment by tsilvs** [comment]
@0xadeeb 

> Why is that no one even knows if the project is abandoned or not?

If you know anyone who is willing to make and maintain a fork - feel free to ask them.

**Comment by liskin** [comment]
> Why is that no one even knows if the project is abandoned or not?

https://github.com/waymonad/waymonad/issues/44#issuecomment-864446327
https://github.com/L-as/waymonad#communication-channels

**Comment by nazzacode** [comment]
Just another comment to say that XMonad is an incredibly important piece of software that deserves an effort to bring a successor to Wayland. Happy to bring some help once we have a maintainer.

**Comment by Ongy** [comment]
I should probably rise up from the "dead".

First a short comment why this thread went like it went... I actually had no energy to concern myself with this project for a while due to a mix of mental health and going from being a student to fulltime work.
And when I first got back to this, it had already gone on for a while, I admit, I was slightly amused to see people ask if a project that hasn't been comitted to in literal *years* is abandoned. Maybe I should have taken a closer look and joined the matrix chat... I think I still idled in the irc channel roughly until freenode died.

I moved the project from my personal account into this one on purpose way back when to allow handing it off with all URLs in place. But never built any kind of community of users. I think the max I knew of was 3, including me.
One other XMonad user that likes new tech, and one that I knew from the qutebrowser irc that just chose my solution to test wayland.

I need to apologize to @L-as. Had I seen your fork in time, I'd probably have given you the keys to this here.
Though I see that you also haven't done any (public?) work in a couple years. Which is hoenstly little surprising to me.

Just to emphasis how much this has always been a "one hero"'s project, the stats from L-as's fork:
```
   499  Markus Ongyerth <ongy@ongy.net>
    59  Las Safin <las@protonmail.ch>
    14  Ongy <ongy44@gmail.com>
     6  Ivan Malison <IvanMalison@gmail.com>
     3  Atemu <atemu.main@gmail.com>
     2  Julius Marozas <marozas.julius@gmail.com>
     2  Las Safin <me@las.rs>
     2  Ongy <ongy@ongy.net>
     2  William Wilhelm <willat8@gmail.com>
     1  L.S. Leary <LSLeary@users.noreply.github.com>
     1  Rosario Pulella <RosarioPulella@gmail.com>
```
I'm top and 3rd spot. I see one serious contributer, one returning and a couple drive bys...
Thanks to everyone that contributed. While I haven't cared for this project in years, I appreciate your time spent to improve it.

The downside... I think making a project of this side work is at least a halftime (~20h/w) time invest. Either from one maintainer that wants to take over, or a group of dedicated contributers.
Let me remind you, there's an associated project https://github.com/swaywm/hsroots/forks?include=active&page=1&period=&sort_by=stargazer_counts which looks equally desolate.
 
Anyways, long story short. I don't have the time and energy anymore to drive this as maintainer/primary contributor.
I don't see a chance for anyone to just come up and say they'll take over as maintainer.
There was one group that did some work during Zurihack iirc. that wanted to but I think that also didn't survive as fork for long...

If you really want this to survive (or rather resurect) I think it's best to just start opening PRs here, or work on your own fork.
A dead project atracts no-one. Including propsective maintainers. An understaffed one might.
Be the change you want to see. I can help anyone that wants to take this serious with some code and concept walkthroughs. But that's the most I expect from myself at least until someone else removed the bitrot and got this back far enough to parity with sway that I would want to switch back on my main system.
And I recommend you rip out everything multi-seat related and go back to the elegance of XMonad zippers... The one regret about this project that still follows me.

**Comment by kittydoor** [comment]
Your arisal is much appreciated! Thank you for updating the mini-community of sorts here. Fingers crossed someone is able to find the time and space and skills and can take this and run with it :)

**Comment by YellowOnion** [comment]
@Ongy Totally understand the mental health stuff, I had a talk to L-as and he said he was working on a DSL of some sort, but it wasn't ready... one thing I would love to see is, since wlroots is C, bindings using linear types, I haven't actually used Xmonad, but I use sway and didn't like how limiting it was from a configuration stand point.

I believe SimulVR is also a wayland compositor written in Haskell, and has a fork of hsroots, their main repot is very active I just not sure what's happening with the wayland side of things...

Maybe I can start tinkering with something when my mental health is decent.

**Comment by L-as** [comment]
A big issue IMO is that wlroots doesn't have any good documentation AFAICT. After all, 1.0 hasn't been released yet!
